name: Black Box CI/CD Pipeline

# Trigger: Run this whenever I push code
on: [push]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Get Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Install Python & Test
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest kafka-python requests elasticsearch

    - name: Run Unit Tests
      run: |
        pytest test_app.py

    # 3. Login to Docker Hub (Using the secrets you just set)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Build and Push the Producer Image
    - name: Build and Push Producer
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # REPLACE 'your-docker-username' BELOW WITH YOUR ACTUAL USERNAME!
        tags: your-docker-username/blackbox-producer:latest